---
- name: update n1 servers
  hosts: n1

  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/walk_dir
        state: directory

    - name: create directory
      file:
        path: /home/ec2-user/walk_dir1
        state: directory

- name: update n2 servers
  hosts: n2

  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/walk_dir1
        state: directory

    - name: create directory
      file:
        path: /home/ec2-user/walk_dir2
        state: directory

- name: update g2 servers
  hosts: g2

  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/walk_dir1
        state: directory

    - name: create directory
      file:
        path: /home/ubuntu/confirm_dir
        state: directory
