---
- name: update u5 servers
  hosts: u5
  become: yes

  tasks:
    - name: Install apache
      apt:
        name: apache2
        state: present

    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install git
      apt:
        name: git
        state: present

    - name: deploy site
      git:
<<<<<<< HEAD
        repo: git@github.com:obongg/food3.git
        dest: /var/www/html
=======
        repo: https://github.com/obongg/food3.git
        dest: /www/var/html
>>>>>>> 7569d0befafa29d5a3467bdf6522d40d7050a89e
