---
- name: update n3 servers
  hosts: n3
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes

- name: update u5 servers
  hosts: u5
  become: yes

  tasks:
    - name: Install apache
      apt:
        name: apache2
        state: present

    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
