---
- name: update g2 servers
  hosts: g2
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Amazon"

    - name: Install apache
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
